### ISSUE TITLE
Combo onPlayerInOut method not getting triggered

### ISSUE THREAD

**Issue by ali-exacute** [mkafrin/PolyZone#80] opened 2023-04-23 08:39 UTC
Only on resource startup it works, and will not print anymore (debug markers showing up correct)

inside a loop

```lua
zones[#zones+1] = CircleZone:Create(blipData.radiusCoord, blipData.radiusRange, {
        name= name..tostring(i),
       useZ=true,
       })
end
```
After loop is done :
```lua
local combo = ComboZone:Create(zones, {name="safezones", debugPoly=true})
combo:onPlayerInOut(function(isPointInside, point, zone)
  print("combo: isPointInside>>", isPointInside)
  print("combo: point>>", point)
  print("combo: zone>>", zone)
end)
```

**Comment by mkafrin** [comment] 2023-05-10 21:49
Are you entering and exiting the zone with the player? The onPlayerInOut callback doesn't trigger continuously, it only triggers if you go from outside the zone to in it, or vice versa. If you are and it's still not working, do you have overlapping zones? Aka multiple zones in the same place, or one large zone with smaller ones inside of it? If so, you may need to use the exhaustive helpers since onPlayerInOut stops after it finds the first zone you are inside of (see https://github.com/mkafrin/PolyZone/wiki/ComboZone#exhaustive-helpers).

Also, are you getting any errors (from your script or PolyZone) in the console?

**Comment by ali-exacute** [comment] 2023-05-16 05:37
hey
1. yes i am entering and exiting the zone
2. no there are no overlapping zones at all
3. sadly there are no errors

**Comment by mkafrin** [comment] 2023-06-09 14:30
Hmm given that, it'd be hard for me to determine what's going wrong without a reproduction of the issue. Can you take your current code and shorten it to a simple and repeatable reproduction of the issue and post that here? Then I can look into why it's happening.

**Comment by PolEpie** [comment] 2023-06-14 01:52
Hi, i have the same thing while drawing a 3d on a separate thread on `function ComboZone:new(zones, options)` 
idk why it happend but all ComboZone stop working and my text work pretty fine ! To fix it i need to reinstall my server cause even on removing my function call on the new function it still not working then even after reboot.
Like ali said there is no errors

**Comment by mkafrin** [comment] 2023-06-14 02:15
This doesn't seem to be a PolyZone issue. Adding a call to your own code to PolyZone's files then it breaking seems to point to your own code having a bug. Closing this for now.

**Closed by mkafrin** 2023-06-14 02:15 UTC

**Comment by PolEpie** [comment] 2023-06-14 10:17
The fact is that is permanently broke poly zone with just one line of code and then it still broke even If i delete the code so there might be an issue somewhere. I’m new in five m coding so if you can help me to understand why ? Is there a thread limit ?

**Comment by mkafrin** [comment] 2023-06-14 10:23
I have no idea why it might be breaking and I'm sorry but I frankly don't have the time to debug other resources code. You can try asking in help channels in the fivem discord or forums. If I were you, I'd test your code (and attempt to fix it) outside the context of PolyZone, since PolyZone breaking is just a symptom of your code that you inserted into it breaking.
